import { Log } from "ethers";
import React, { FC, memo, useEffect, useContext } from "react";
import { useLocation } from "react-router";
import ContentFrame from "../../components/ContentFrame";
import LogEntry from "./LogEntry";
import {usePageTitle} from '../../useTitle';
import {Helmet} from 'react-helmet-async';
import { SelectedTransactionContext } from "../../useSelectedTransaction";

type LogsProps = {
  logs: Log[] | undefined;
  txHash: string;
};

const Logs: FC<LogsProps> = ({ logs, txHash }) => {
  const location = useLocation();
  const txData = useContext(SelectedTransactionContext);

  useEffect(() => {
    setTimeout(() => {
      if (location.hash) {
        // Scroll to fragment, e.g. "#3"
        let foundElement = document.getElementById(location.hash.slice(1));
        if (foundElement) {
          foundElement.scrollIntoView({
            behavior: "smooth",
          });
        }
      }
    }, 200);
  }, [logs]);

  usePageTitle(`Logs - Transaction ${txHash}`);

  const description = `View logs for Ethereum transaction ${txHash}, including emitted events and contract interactions.`

  const schemaData: any = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "url": `https://ethscan.org/tx/${txHash}/logs`,
    "name": `Transaction Logs ${txHash}`,
    "description": description,
  };

  // Only include mainEntity for transactions with value > 0 ETH
  if (txData && txData.value && txData.value > 0n) {
    schemaData.mainEntity = {
      "@type": "DigitalDocument",
      "identifier": `${txHash}`,
      "name": `Transaction Logs ${txHash}`,
      "description": "Event logs generated by smart contract execution"
    };
  }

  const payloadSchemaWebPage = JSON.stringify(schemaData);

  return (
    <ContentFrame tabs>
      <Helmet>
        <meta name="description" content={description}/>
        <link rel="canonical" href={`https://ethscan.org/tx/${txHash}/logs`} />
        <script type="application/ld+json">{payloadSchemaWebPage}</script>
      </Helmet>
      {logs && (
        <>
          {logs.length > 0 ? (
            <>
              {logs.map((l, i) => (
                <LogEntry key={i} log={l} />
              ))}
            </>
          ) : (
            <div className="py-4 text-sm">Transaction didn't emit any logs</div>
          )}
        </>
      )}
    </ContentFrame>
  );
};

export default memo(Logs);
